version: '3.8'

services:  # Serviços que serão orquestrados
  node:  # Serviço que usa a imagem Node.js
    image: node:22.11.0
    container_name: nodeExpo
    working_dir: /app
    volumes:
      - ./:/app  # Mapeia o diretório atual para o diretório /app no contêiner
      - ./node_modules:/app/node_modules  # Evita que o diretório node_modules local sobrescreva o contêiner
    ports:
      - 19000:19000  # Porta para o Expo
      - 19001:19001  # Porta para o Expo
      - 19002:19002  # Porta para o Expo
      - 8081:8081    # Porta padrão do servidor React Native (Expo)
    networks:
      - appExpo  # Define que o contêiner estará na rede 'appExpo'
    command: >  # Comando para manter o contêiner rodando
      sh -c "tail -f /dev/null"

  jdk:  # Serviço que usa a imagem OpenJDK
    image: openjdk:17-jdk
    container_name: jdk
    working_dir: /app
    networks:
      - appExpo  # Define que o contêiner estará na rede 'appExpo'
    command: tail -f /dev/null  # Mantém o contêiner JDK em execução sem fazer nada

networks:  # Definição das redes Docker
  appExpo:  # Rede chamada 'appExpo'
    driver: bridge  # Usando o driver padrão 'bridge' para comunicação entre contêineres